class BaseEngine:
    name: str = "[BASE ENGINE]"

    def init(self, _fen: str | None = None) -> None:
        """ Initializes the engine.

        Param fen: FEN representation of the initial state. If None then it 
                   should be the starting position.
        Returns: the move it found in Long Algebraic Notation (LAN).

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")

    def go(self, _msLeft: int) -> str:
        """ Searches for the best move given the amount of time left.

        Param msLeft: Remaining time to move in milliseconds.
        Returns: The move it found in Long Algebraic Notation (LAN).

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")

    def move(self, _move: str) -> None:
        """ Applies a move to the internal state of the engine.

        Param move: The move to make in Long Algebraic Notation (LAN)

        This move may or may not be generated by the engine. Internal state 
        should be updated accordingly.

        The engine is expected to function in accordance with the rules, no 
        further validation is performed.
        """
        raise NotImplementedError("Please implement this method")
